version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /tools
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      go-and-tools:
        applies-to: version-updates
        patterns:
          - "*"
      go-and-tools-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      docker-inputs:
        applies-to: version-updates
        patterns:
          - "*"
      docker-inputs-security:
        applies-to: security-updates
        patterns:
          - "*"
